/**
 * Created by ysc1 on 11/13/2016.
 */
class StateConstants {
    static AB = "Abia"
    static AD = "Adamawa"
    static AI = "Akwa Ibom"
    static AS = "Anambra State"
    static BA = "Bauchi"
    static BY = "Bayelsa"
    static BE = "Benue"
    static BO = "Borno"
    static CR = "Cross River"
    static De = "Delta"
    static EB = "Ebonyi"
    static ED = "Edo"
    static EK = "Ekiti"
    static EN = "Enugu"
    static GO = "Gombe"
    static IM = "Imo"
    static JI = "Jigawa"
    static KA = "Kaduna"
    static KN = "Kano"
    static KT = "Katsina"
    static KB = "Kebbi"
    static KO = "Kogi"
    static KW = "Kwara"
    static LA = "Lagos"
    static NA = "Nasarawa"
    static NI = "Niger"
    static OG = "Ogun"
    static ON = "Ondo"
    static OS = "Osun"
    static OY = "Oyo"
    static PL = "Plateau"
    static RI = "Rivers"
    static SO = "Sokoto"
    static TA = "Taraba"
    static YO = "Yobe"
    static ZA = "Zamfara"
}
